version: "1.0"

volumes:
  db_data:

services:
  database:
    image: postgres:14.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: trpc_authentication
    volumes:
      - db_data:/var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm
